import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ weight: "400", preload: false });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
        style={{ backgroundColor: "#efeae4" }}
      >
        {children}
      </body>
    </html>
  );
}
